CREATE TABLE IF NOT EXISTS `#__ec_user` (
	`user` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT, 
	`modified` DATETIME NOT NULL DEFAULT '2015-01-01 00:00:00',
	`profile` VARCHAR(5120) NOT NULL DEFAULT '',
	`option` VARCHAR(5120) NOT NULL DEFAULT '',
	PRIMARY KEY (`user`),
	KEY `idx_modified` (`modified`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;